# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for rubocop
    config: './rubocop.yml'

# add the files here you want to be ignored by stickler
files:
  ignore:
    - "bin/*"
    - "test/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Gemfile"
    - "Rakefile"
    - "README.md"
    - "node_modules/**/*"
    - "app/views/**/*"
    - "app/controllers/users/*"

fixers:
  enable: true
